# Generated by Django 4.2.1 on 2023-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ll',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=10),
        ),
    ]
