# Generated by Django 4.2.1 on 2023-05-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='ll',
        ),
    ]
