# Generated by Django 4.2.1 on 2023-05-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up', models.CharField(max_length=155)),
                ('delivery', models.CharField(max_length=155)),
                ('weight', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
